name: "💡 Feature Request"
description: Create a new ticket for a new feature request
labels: ["enhancement", "needs triage"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution you'd like
      description: Provide a clear and concise description of what you want to happen. Add any considered drawbacks. Feel free to add some code if you want 😎
      placeholder: Describe in a few lines your solution idea with any considered drawbacks.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/fonzdm/servarr/servarr-chartCONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
