apiVersion: v2
name: servarr
description: Servarr complete Helm Chart for Kubernetes
type: application
version: 1.0.1
appVersion: "1.0.0"
keywords:
  - servarr
  - prowlarr
  - radarr
  - sonarr
  - qbittorrent
  - jellyseerr
  - jellyfin
  - flaresolverr
home: https://github.com/fonzdm/servarr
sources:
  - https://github.com/fonzdm/servarr
dependencies:
  - name: sonarr
    version: "23.6.4"
    repository: "oci://tccr.io/truecharts"
    # condition: sonarr.enabled
    tags:
      - tvseries
  - name: radarr
    version: "23.18.0"
    repository: "oci://tccr.io/truecharts"
    # condition: radarr.enabled
    tags:
      - movies
  - name: prowlarr
    version: "18.15.2"
    repository: "oci://tccr.io/truecharts"
    # condition: prowlarr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: qbittorrent
    version: "22.4.4"
    repository: "oci://tccr.io/truecharts"
    # condition: qbittorrent.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: jellyseerr
    version: "12.6.1"
    repository: "oci://tccr.io/truecharts"
    # condition: jellyseerr.enabled
    tags:
      - movies
      - tvseries
  - name: jellyfin
    version: "20.6.9"
    repository: "oci://tccr.io/truecharts"
    # condition: jellyfin.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: flaresolverr
    version: "15.5.1"
    repository: "oci://tccr.io/truecharts"
    # condition: flaresolverr.enabled
    tags:
      - movies
      - tvseries
      - music
annotations:
  artifacthub.io/alternativeName: servar
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: fonzdm
      email: adm220297@proton.me
    - name: imgios
      email: g.sulipano@outlook.it
    - name: mrgionsi
      email: g.pasquariello96@gmail.com
    - name: lucaam
      email: luca.amoriello@hotmail.it

maintainers:
  - name: Alfonso De Masi
    email: adm220297@proton.me
