apiVersion: v2
name: servarr
description: Servarr complete Helm Chart for Kubernetes
type: application
version: 1.0.2
appVersion: "1.0.0"
keywords:
  - servarr
  - prowlarr
  - radarr
  - sonarr
  - qbittorrent
  - jellyseerr
  - jellyfin
  - flaresolverr
  - scraparr
home: https://github.com/fonzdm/servarr
sources:
  - https://github.com/fonzdm/servarr
dependencies:
  - name: sonarr
    version: "21.2.1"
    repository: "oci://tccr.io/truecharts"
    # condition: sonarr.enabled
    tags:
      - tvseries
  - name: radarr
    version: "21.2.1"
    repository: "oci://tccr.io/truecharts"
    # condition: radarr.enabled
    tags:
      - movies
  - name: prowlarr
    version: "16.2.1"
    repository: "oci://tccr.io/truecharts"
    # condition: prowlarr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: qbittorrent
    version: "19.4.1"
    repository: "oci://tccr.io/truecharts"
    # condition: qbittorrent.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: jellyseerr
    version: "9.5.2"
    repository: "oci://tccr.io/truecharts"
    # condition: jellyseerr.enabled
    tags:
      - movies
      - tvseries
  - name: jellyfin
    version: "18.7.7"
    repository: "oci://tccr.io/truecharts"
    # condition: jellyfin.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: flaresolverr
    version: "13.4.1"
    repository: "oci://tccr.io/truecharts"
    # condition: flaresolverr.enabled
    tags:
      - movies
      - tvseries
      - music
  - name: scraparr
    version: "1.0.1"
    repository: "https://github.com/imgios"
    # condition: scraparr.enabled
    tags:
      - metrics
annotations:
  artifacthub.io/alternativeName: servar
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: AGPL-3.0-or-later
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: fonzdm
      email: adm220297@proton.me
    - name: imgios
      email: g.sulipano@outlook.it
    - name: mrgionsi
      email: g.pasquariello96@gmail.com
    - name: lucaam
      email: luca.amoriello@hotmail.it

maintainers:
  - name: Alfonso De Masi
    email: adm220297@proton.me
