{{- if .Values.initJellyseerr -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: jellyseer-init
  labels:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "40"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}-jellyseer-finalizer"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-jellyseerr
          image: busybox:1.37.0
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "until wget --spider -S -T 10 \"http://{{ .Release.Name }}-jellyseerr.{{ .Release.Namespace }}.svc.cluster.local:10241\" 2>&1 | grep -qw '200\\|301\\|302' > /dev/null ; do echo Waiting for servarr-jellyseerr ; sleep 5 ; done ; sleep 10 ;"
      containers:
      - name: initialize-jellyseer
        image: python:3.10
        imagePullPolicy: IfNotPresent
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: JELLYSEERR_HOST
            value: "{{ .Release.Name }}-jellyseerr.{{ .Release.Namespace }}.svc.cluster.local"
          - name: JELLYSEERR_PORT
            value: "10241"
          - name: JELLYFIN_HOST
            value: "{{ .Release.Name }}-jellyfin"
          - name: JELLYFIN_PORT
            value: "8096"
          - name: JELLYFIN_USERNAME
            value: "{{ $.Values.dash.username }}"
          - name: JELLYFIN_PASSWORD
            value: "{{ $.Values.dash.password }}"
          - name: JELLYFIN_EMAIL
            value: "{{ $.Values.dash.mail }}"
          - name: API_KEY
            value: "{{ $.Values.global.apikey }}"
          - name: TELEGRAM_NOTIFICATION_ENABLED
            value: "{{ $.Values.notifications.telegram.enabled }}"
          - name: TELEGRAM_CHAT_ID
            value: "{{ $.Values.notifications.telegram.chat_id}}"
          - name: TELEGRAM_BOT_APITOKEN
            value: "{{ $.Values.notifications.telegram.bot_apitoken }}"
        command:
          - "/bin/sh"
          - "-ec"
        args:
          - "pip install requests && python3 -u /mnt/init-jellyseerr.py 2>&1;"
        volumeMounts:
          - mountPath: "/mnt"
            name: python-script
      volumes:
        - name: python-script
          configMap:
            name: init-jellyseerr-python-scripts

{{- end }}
