---

apiVersion: v1
kind: Secret
metadata:
  name: servarr-api-key
type: Opaque
stringData:
  apikey: {{ .Values.global.apikey }}


---

apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-creds
type: Opaque
stringData:
  username: {{ .Values.torrent.username }}
  password: {{ .Values.torrent.password }}
