name: "Helm Chart Doc Generator"

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to current commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run helm-docs and push to the same branch
        uses: losisin/helm-docs-github-action@v1
        with:
          git-push: true
          git-push-user-name: "Servarr Bot 🤖"
          git-push-user-email: "servarr-bot@fonzdm.xyz"
          chart-search-root: ./servarr/servarr-chart
