name: Helm Chart Lint & Build

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.1.0
        with:
          version: v3.13.0

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs=servarr/servarr-chart --charts=servarr/servarr-chart --validate-maintainers=false

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.1.0

      - name: Helm Dependency update
        run: helm dependency update servarr/servarr-chart --debug

      - name: Helm Template
        run: helm template servarr servarr/servarr-chart --debug -f .github/ci/ci-values.yaml

      - name: Create Package
        run: helm package servarr/servarr-chart
